FROM python:3.9.5

COPY ./common/python_utils /opt/app/common/python_utils
COPY ./core/cli /opt/app/core/cli

WORKDIR /opt/app/core/cli
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/app/core/cli/src
ENTRYPOINT [ "python", "main.py" ]