FROM python:3.10.2-slim-buster

RUN apt-get update && \
    apt-get install --no-install-recommends build-essential=12.6 libpq-dev=\* -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./core/backend /opt/core/backend

WORKDIR /opt/core/backend

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/core/backend/app

ENTRYPOINT [ "python", "main.py" ]