FROM python:3.9.5-slim-buster

RUN apt-get update && \
    apt-get install --no-install-recommends build-essential=12.6 libpq-dev=\* -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./core/backend /opt/core/backend

WORKDIR /opt/core/backend

RUN DBT_PSYCOPG2_NAME=psycopg2 pip install --no-cache-dir -r requirements.txt --no-binary dbt-postgres

WORKDIR /opt/core/backend/app

ENTRYPOINT [ "python", "main.py" ]