FROM kuwala/base-images:python-java-0.2.0-alpha

RUN apt-get update && \
    apt-get install --no-install-recommends build-essential=12.6 libpq-dev=\* -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./core/database/importer /opt/core/database/importer

WORKDIR /opt/core/database/importer
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/core/database/importer/src
ENTRYPOINT [ "python", "main.py" ]