FROM kartoza/postgis:14-3.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends cmake=\* gcc=\* git=\* libtool=\* make=\* python3=\* python3-pip=\* \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --no-cache-dir --upgrade pip==21.3.1 setuptools==60.2.0 && pip3 install --no-cache-dir pgxnclient==1.3.2 \
    && pgxn install h3 \
    && mkdir -p /docker-entrypoint-initdb.d
