FROM kuwala/base-images:python-java-0.2.0-alpha

COPY ./pipelines/google-trends /opt/pipelines/app

WORKDIR /opt/pipelines/app
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/pipelines/app/src
ENTRYPOINT [ "python", "main.py" ]