import {library} from "@fortawesome/fontawesome-svg-core";
import {
    faAlignLeft,
    faArrowDown,
    faArrowUp,
    faCalculator,
    faCalendarDay,
    faChartPie,
    faCheck,
    faCheckCircle,
    faClock,
    faCogs,
    faDivide,
    faFileCsv,
    faFileExport,
    faFilter,
    faGreaterThan,
    faGreaterThanEqual,
    faLayerGroup,
    faLink,
    faMapMarkedAlt,
    faPaste,
    faPlus,
    faShareFromSquare,
    faShuffle,
    faSyncAlt,
    faTimes,
    faTimesCircle,
    faQuestion,
    faWindowRestore
} from "@fortawesome/free-solid-svg-icons";

const icons = () => {
    library.add(
        faAlignLeft,
        faArrowDown,
        faArrowUp,
        faCalculator,
        faCalendarDay,
        faChartPie,
        faCheck,
        faCheckCircle,
        faClock,
        faCogs,
        faDivide,
        faFileCsv,
        faFileExport,
        faFilter,
        faGreaterThan,
        faGreaterThanEqual,
        faLayerGroup,
        faLink,
        faMapMarkedAlt,
        faPaste,
        faPlus,
        faShareFromSquare,
        faShuffle,
        faSyncAlt,
        faTimes,
        faTimesCircle,
        faQuestion,
        faWindowRestore
    )
}

export default icons;
