FROM jupyter/pyspark-notebook


# Install Jupyter Notebook, Lab, and Hub
# Generate a notebook server config
# Cleanup temporary files
# Correct permissions
# Do all this in a single RUN command to avoid duplicating all of the
# files across image layers when the permissions change
RUN conda install --quiet --yes \
    'geojson' \
    'h3-py' \
    'neo4j-python-driver' && \
    conda clean --all -f -y

# Setup work directory for backward-compatibility
RUN mkdir "/home/${NB_USER}/kuwala" && \
    mkdir "/home/${NB_USER}/kuwala/modules" && \
    mkdir "/home/${NB_USER}/kuwala/notebooks" && \
    touch "/home/${NB_USER}/kuwala/__init__.py" && \
    fix-permissions "/home/${NB_USER}"

COPY ./common/jupyter/modules "/home/${NB_USER}/kuwala/modules" 
COPY ./common/jupyter/notebooks "/home/${NB_USER}/kuwala/notebooks" 

ENV PYTHONPATH="/home/${NB_USER}/"