FROM jupyter/pyspark-notebook

COPY ./common/jupyter/requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt

# Setup work directory for backward-compatibility
RUN mkdir "/home/${NB_USER}/kuwala" && \
    mkdir "/home/${NB_USER}/kuwala/modules" && \
    mkdir "/home/${NB_USER}/kuwala/notebooks" && \
    touch "/home/${NB_USER}/kuwala/__init__.py" && \
    fix-permissions "/home/${NB_USER}"

COPY ./common/jupyter/modules "/home/${NB_USER}/kuwala/modules" 
COPY ./common/jupyter/notebooks "/home/${NB_USER}/kuwala/notebooks" 

ENV PYTHONPATH="/home/${NB_USER}/"