FROM rappdw/docker-java-python

COPY ./common/python_utils /opt/common/python_utils
COPY ./core/neo4j /opt/core/app

WORKDIR /opt/core/app/importer
RUN pip install -r requirements.txt

WORKDIR /opt/core/app/importer/src
ENTRYPOINT [ "python", "-u", "main.py" ]