### 1. Get Linux
FROM rappdw/docker-java-python

COPY ./core/neo4j/importer /opt/app

WORKDIR /opt/app
RUN pip install -r requirements.txt

WORKDIR /opt/app/src
ENTRYPOINT [ "python", "-u", "main.py" ]