FROM rappdw/docker-java-python

COPY ./common/python_utils /opt/app/common/python_utils
COPY ./pipelines/population-density /opt/app/pipelines/population-density

WORKDIR /opt/app/pipelines/population-density
RUN pip install -r requirements.txt

WORKDIR /opt/app/pipelines/population-density/src
ENTRYPOINT [ "python", "main.py" ]