FROM rappdw/docker-java-python

COPY ./pipelines/common/python_utils /opt/common/python_utils
COPY ./pipelines/population-density /opt/app

WORKDIR /opt/app
RUN pip install -r requirements.txt

WORKDIR /opt/app/src
ENTRYPOINT [ "python", "main.py" ]