FROM rappdw/docker-java-python:zulu11.43-python3.7.9

COPY ./common/python_utils /opt/app/common/python_utils
COPY ./pipelines/osm-poi /opt/app/pipelines/osm-poi

WORKDIR /opt/app/pipelines/osm-poi
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/app/pipelines/osm-poi/src
ENTRYPOINT [ "python", "main.py" ]