FROM rappdw/docker-java-python

COPY ./common/python_utils /opt/app/common/python_utils
COPY ./pipelines/osm-poi /opt/app/pipelines/osm-poi

WORKDIR /opt/app/pipelines/osm-poi
RUN pip install -r requirements.txt

WORKDIR /opt/app/pipelines/osm-poi/src
ENTRYPOINT [ "python", "main.py" ]