FROM python:3.9.5

COPY ./common/python_utils /opt/common/python_utils
COPY ./google-poi /opt/app

ENV PYTHONPATH="/opt/common:/opt/app"

WORKDIR /opt/app
RUN pip install -r requirements.txt

WORKDIR /opt/app/src
ENTRYPOINT [ "python", "-u", "app.py", "local" ]