FROM rappdw/docker-java-python

COPY ./common/python_utils /opt/common/python_utils
COPY ./pipelines/google-poi /opt/pipelines/app

WORKDIR /opt/pipelines/app
RUN pip install -r requirements.txt

WORKDIR /opt/pipelines/app/src/pipeline
ENTRYPOINT [ "python", "main.py" ]