FROM rappdw/docker-java-python

COPY ./pipelines/common/python_utils /opt/common/python_utils
COPY ./pipelines/google-poi /opt/pipeline

WORKDIR /opt/pipeline
RUN pip install -r requirements.txt

WORKDIR /opt/pipeline/src/pipeline
ENTRYPOINT [ "python", "main.py" ]