FROM rappdw/docker-java-python

COPY ./common/python_utils /opt/app/common/python_utils
COPY ./pipelines/google-poi /opt/app/pipelines/google-poi

WORKDIR /opt/app/pipelines/google-poi
RUN pip install -r requirements.txt

WORKDIR /opt/app/pipelines/google-poi/src/pipeline
ENTRYPOINT [ "python", "main.py" ]