FROM maven
COPY ./core/neo4j/plugins/udfs /usr/src/mymaven
WORKDIR /usr/src/mymaven
RUN mvn clean install

FROM neo4j:4.3.0-community
COPY --from=0 /usr/src/mymaven/target/cypher-udfs-0.1-SNAPSHOT.jar ./plugins/cypher-udfs-0.1-SNAPSHOT.jar
