FROM python:3.9.5

COPY ./pipelines/common/python_utils /opt/common/python_utils
COPY ./pipelines/google-poi /opt/app

WORKDIR /opt/app
RUN pip install -r requirements.txt

WORKDIR /opt/app/src
ENTRYPOINT [ "python", "-u", "app.py", "local" ]