FROM node:alpine

COPY ./common/js_utils /opt/common/js_utils
COPY ./population-density /opt/app

# awscli is in use in our node app, we meed to install it in the docker image
RUN apk add --no-cache \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
        awscli \
    && rm -rf /var/cache/apk/*

# Setting up a virtual build env in order to keep the image small
RUN apk add --no-cache --virtual .gyp \
        g++ gcc libgcc libstdc++ linux-headers make bash git cmake && \
        npm install --quiet node-gyp -g

#Setting up 
WORKDIR /opt/common/js_utils
RUN npm ci

WORKDIR /opt/app
RUN npm ci

# Deleting the virtual build env in order to keep the image small
RUN apk del .gyp

WORKDIR /opt/app

ENTRYPOINT ["npm","run"]
