FROM node:alpine

COPY ./shared /opt/shared
COPY ./population-density /opt/population-density

# Setting up a virtual build env in order to keep the image small
RUN apk add --no-cache --virtual .gyp \
        g++ gcc libgcc libstdc++ linux-headers make python2 bash git cmake && \
            npm install --quiet node-gyp -g

#Setting up 
WORKDIR /opt/shared/js
RUN npm ci

WORKDIR /opt/population-density
RUN npm ci

# Deleting the virtual build env in order to keep the image small
RUN apk del .gyp

WORKDIR /opt/population-density
CMD ["npm","run","start-processing:local" ]
