ARG IMAGE_VARIANT=slim-buster
ARG OPENJDK_VERSION=8
ARG PYTHON_VERSION=3.10.2

FROM python:${PYTHON_VERSION}-${IMAGE_VARIANT} AS py3
FROM openjdk:${OPENJDK_VERSION}-${IMAGE_VARIANT}

COPY --from=py3 / /

RUN apt-get update && \
    apt-get install --no-install-recommends build-essential=12.6 -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*