name: Build frontend Docker image
on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: kuwala/core/canvas/dockerfile
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # This is a separate action that sets up buildx runner
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # So now you can use Actions' own caching!
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # And make it available for the builds
    - name: Build frontend and push
      uses: docker/build-push-action@v2
      with:
        context: kuwala
        file: kuwala/core/canvas/dockerfile
        push: false
        tags: kuwala/frontend:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new